stages:
- name: Maven编译
  steps:
  - runScriptConfig:
      image: maven:3.8.1-jdk-8-slim
      shellScript: |-
        LOG_TAG="CHIP-INFO"
        MVN_SETTINGS_PATH="/root/.m2"
        echo "[$LOG_TAG]Current pwd:`pwd`"
        ls -l
        echo "[$LOG_TAG]===========Execute Maven CMD Build Project Start==========="
        mvn clean package -Dmaven.test.skip=true
        echo "[$LOG_TAG]===========Execute Maven CMD Build Project End==========="
        echo "[$LOG_TAG]Dir:target ls -l:`pwd`"
        ls -l ./target
- name: 构建镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: rancher-demo:1.0
- name: 部署
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
