apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rancher-demo
        track: stable
    spec:
      containers:
        - name: rancher-demo
          image: rancher-demo:1.0
          ports:
            - containerPort: 8080